# Generated by Django 6.0.3 on 2026-03-11 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Employee_id', models.IntegerField()),
                ('Employee_name', models.CharField(max_length=30)),
                ('Email', models.EmailField(max_length=254)),
                ('PhoneNumber', models.IntegerField()),
                ('Designation', models.CharField(max_length=50)),
                ('Salary', models.IntegerField()),
                ('Image', models.ImageField(upload_to='employee')),
            ],
        ),
    ]
